### PR TITLE
Features

### PR DESCRIPTION
**Pull request by NiiazalyDzhumaliev**
I made Newsweek clone with Bootstrap. Please, review my project.

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 🐱

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Great Job @NiiazalyDzhumaliev  🎉🎉🎉

**You've done quite well on this project.👏**

Your project looks awesome, particularly with the screen breakpoints on the page and implementing it at the right media query.

There are however a few changes that need to be made before proceeding:👇

- [x] Required - Kindly fix the HTML validation errors picked by this validator [tool](https://validator.w3.org/nu/) on your HTML file.
Ensure there are no errors in your HTML code.

- [x] Required - Also in the `Featured Slideshows` section of the page just before the footer. There is a limited number of templates in yours. The original template has seven(7) templates, but yours has only two(2) templates. Kindly add more sections to yours.
ice_screenshot_20200401-102241

- [ ] Required - There are sections on your page that are expected to be page links but are just plain text. Kindly fix these sections:

**THE LATEST NEWS SECTION IS EXPECTED TO BE A LINK👇**
ice_screenshot_20200401-095250

**ALSO, THE MORE STORIES SECTION IS EXPECTED TO BE A LINK👇**
ice_screenshot_20200401-095318

**THE SUBSCRIBE AND SIGN IN BUTTONS AT THE HEADER SHOULD BE LINKS👇**
ice_screenshot_20200401-100100

- [ ] Optional - Kindly spread out the social icons at the page bottom close to the footer section.
ice_screenshot_20200401-095439

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by NiiazalyDzhumaliev** [comment]
Thanks for the reasonable comments. I corrected all of them, also the optional one. Please kindly check again.

**Comment by Dandush03** [comment]
### :heavy_check_mark: Project Approve :exploding_head: :checkered_flag:
# Hey @NiiazalyDzhumaliev  :+1: 
### Great Job so Far :grey_exclamation: :grey_exclamation: :muscle: :smiley: 

### Following Previous Reviews and Seeing you Have Made Required Changes. 
### The project Looks Great.:grey_exclamation::wink:.

## [_Optional_]
* [ ] add a max-width do the project so it would actually look like the original page
Screenshot from 2020-04-01 08-45-43


### Good Luck in your Next Assigment
### Happy coding:computer: 
#### Daniel Laloush

**Pull request merged**
